// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt_KsDrh6gSnW2FdeifBQz3uYD8fYT2yU',
    appId: '1:1089973154276:android:a7ff3a7348e2d1705d17f1',
    messagingSenderId: '1089973154276',
    projectId: 'app-fiscalizacion-joya',
    databaseURL: 'https://app-fiscalizacion-joya-default-rtdb.firebaseio.com',
    storageBucket: 'app-fiscalizacion-joya.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7T1HyfND4gzO5ON6oX2E6MJFEHwVs7FM',
    appId: '1:1089973154276:web:71bf22912cccafb95d17f1',
    messagingSenderId: '1089973154276',
    projectId: 'app-fiscalizacion-joya',
    authDomain: 'app-fiscalizacion-joya.firebaseapp.com',
    databaseURL: 'https://app-fiscalizacion-joya-default-rtdb.firebaseio.com',
    storageBucket: 'app-fiscalizacion-joya.firebasestorage.app',
  );

}